In [4]:
import pandas as pd 
import numpy as np

Repaso de numpy


Copiar arreglos

In [3]:
arr1 = np.array(range(10))

In [6]:
# Copiar
tmp = arr1

In [7]:
print(arr1, tmp)

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9]


In [8]:
arr1[0] = 100

In [9]:
print(arr1, tmp)

[100   1   2   3   4   5   6   7   8   9] [100   1   2   3   4   5   6   7   8   9]


In [10]:
arr1 = np.array(range(10))

tmp = arr1.copy()
# Lo que se utiliza es para crear otra versión con un espacio de memoria diferente
# Al hacer cualquier modficación a alguno, no se verá afectado el otro

In [11]:
print(arr1, tmp)

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9]


In [12]:
arr1[-1] = 100

In [13]:
print(arr1, tmp)

[  0   1   2   3   4   5   6   7   8 100] [0 1 2 3 4 5 6 7 8 9]


Pandas

In [5]:
serie1 = pd.Series([1, 2, 3, 4, 5])

In [15]:
type(serie1)

pandas.core.series.Series

In [17]:
serie1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [16]:
serie1[0]

np.int64(1)

In [19]:
serie1[2:3]

2    3
dtype: int64

In [20]:
serie1 + 10

0    11
1    12
2    13
3    14
4    15
dtype: int64

In [22]:
serie2 = serie1.copy
serie1[-1] = 500

print(serie1, serie2)

 0      1
 1      2
 2      3
 3      4
 4      5
-1    500
dtype: int64 <bound method NDFrame.copy of  0      1
 1      2
 2      3
 3      4
 4      5
-1    500
dtype: int64>


In [7]:
def f(x):
    if x % 2 ==0:
        return 100
    else:
        return None

In [8]:
serie1.apply(f)

0      NaN
1    100.0
2      NaN
3    100.0
4      NaN
dtype: float64

In [9]:
import math

In [10]:
serie1.apply(math.sqrt)

0    1.000000
1    1.414214
2    1.732051
3    2.000000
4    2.236068
dtype: float64

In [ ]:
df  = pd.DataFrame(range(1, 11))