# Práctica 1

## Nombre del equipo:
    Master Parsers

## Miembros del equipo:
    - José Gabriel Hernández Castresana
    - Alejandro Guerrero Alvarez
    - Juan Pablo Jiménez Salazar
    - Carlos Flores Vara
    - Armando Guzmán Ramírez

Objetivo: 
    Construir una matriz booleana a partir de la bolsa de palabras generada del texto original.
    Para esto vamos a verificar si las palabras que se encuentran en la bolsa de palabras, también se encuentra en cada una de las oraciones.
    Si se encuentra en la oración, es 1, de lo contrario es 0

---

A continuación se importan las librerías que vamos a utilizar las cuales son las siguientes:
- NLTK
- re
- numpy
- Pandas
- Stopwords

In [2]:
import nltk
import re
import numpy as np 
import pandas as pd
from nltk.corpus import stopwords


En la siguiente línea lo que realizamos guardar el texto original a trabajar en la variable "text_original"

In [3]:
text_original = '''Helen is unhappy with her mother. Her mother is unhappy with Helen. They are both unhappy with each other. Helen has a boyfriend. His name is Peter. Her mother doesn't like Peter. Her mother said that Peter is rude. Why did she say that? Because Peter didn't take his hat off in the house. Helen's mother says that is rude. A man should take his hat off in the house. "Your father always took his hat off in the house," Helen's mother said. "But, Mom, times are different now," Helen said. "I promise you, Peter will take his hat off next time." Helen's mother said it was too late - rude is rude.'''

En la siguiente línea se convierten a minúsculas todas las letras del texto

In [4]:
min_text= text_original.lower()

En la siguiente línea se elimina los signos de puntuación del texto original para dejar sólo las palabras

In [5]:
cl_txt = re.sub(r"\W"," ",min_text)


Se imprime el texto con las puras palabras, sin los signos de puntuación

In [6]:
cl_txt

'helen is unhappy with her mother  her mother is unhappy with helen  they are both unhappy with each other  helen has a boyfriend  his name is peter  her mother doesn t like peter  her mother said that peter is rude  why did she say that  because peter didn t take his hat off in the house  helen s mother says that is rude  a man should take his hat off in the house   your father always took his hat off in the house   helen s mother said   but  mom  times are different now   helen said   i promise you  peter will take his hat off next time   helen s mother said it was too late   rude is rude '

En la siguiente línea se tokeniza el texto ya limpio de todos los signos de puntuación

In [7]:
tk_text= nltk.word_tokenize(cl_txt)

Se imprime la lista de palabras ya tokenizadas

In [8]:
tk_text

['helen',
 'is',
 'unhappy',
 'with',
 'her',
 'mother',
 'her',
 'mother',
 'is',
 'unhappy',
 'with',
 'helen',
 'they',
 'are',
 'both',
 'unhappy',
 'with',
 'each',
 'other',
 'helen',
 'has',
 'a',
 'boyfriend',
 'his',
 'name',
 'is',
 'peter',
 'her',
 'mother',
 'doesn',
 't',
 'like',
 'peter',
 'her',
 'mother',
 'said',
 'that',
 'peter',
 'is',
 'rude',
 'why',
 'did',
 'she',
 'say',
 'that',
 'because',
 'peter',
 'didn',
 't',
 'take',
 'his',
 'hat',
 'off',
 'in',
 'the',
 'house',
 'helen',
 's',
 'mother',
 'says',
 'that',
 'is',
 'rude',
 'a',
 'man',
 'should',
 'take',
 'his',
 'hat',
 'off',
 'in',
 'the',
 'house',
 'your',
 'father',
 'always',
 'took',
 'his',
 'hat',
 'off',
 'in',
 'the',
 'house',
 'helen',
 's',
 'mother',
 'said',
 'but',
 'mom',
 'times',
 'are',
 'different',
 'now',
 'helen',
 'said',
 'i',
 'promise',
 'you',
 'peter',
 'will',
 'take',
 'his',
 'hat',
 'off',
 'next',
 'time',
 'helen',
 's',
 'mother',
 'said',
 'it',
 'was',
 'to

Se mandan a llamar la lista en inglés de palabras vacías

In [9]:
stp_wds= stopwords.words('english')

Se hace la busqueda de la lista de palabras vaacías en la lista de tokens.
Una vez que se encuentren las palabras vacías, las demás palabras se van a agregar a una nueva lista con el nombre: "flt_words"

In [10]:
flt_words = [w for w in tk_text if w not in stp_wds]

Se hace el conteo de las palabras filtradas

In [11]:
len(flt_words)

56

Se crea un diccionario con el nombre de "vocabulary", en el cuál se eliminan las palabras repetidas

In [12]:
vocabulary = set(flt_words)

Se cuentan el número de elementos en el diccionario vocabulary

In [13]:
len(vocabulary)

25

Se crea un diccionario con el nombre de frecs

In [14]:
frecs = {}

En el siguiente ciclo se cuenta el número de veces que aparecen las palabras en la lista "flt_words".
Para hacer el conteo de palabras se utiliza como llave la palabra, y después se agrega la palabra con su frecuencia en el diccionario de frecuencias.

In [15]:
for word in flt_words: 
    if word not in frecs.keys():
        frecs[word] = 1
    else:
        frecs[word] += 1

Se imprime el contenido del diccionario

In [16]:
frecs

{'helen': 7,
 'unhappy': 3,
 'mother': 7,
 'boyfriend': 1,
 'name': 1,
 'peter': 5,
 'like': 1,
 'said': 4,
 'rude': 4,
 'say': 1,
 'take': 3,
 'hat': 4,
 'house': 3,
 'says': 1,
 'man': 1,
 'father': 1,
 'always': 1,
 'took': 1,
 'mom': 1,
 'times': 1,
 'different': 1,
 'promise': 1,
 'next': 1,
 'time': 1,
 'late': 1}

Se declara de nuevo el texto un otra variable de nombre "text_2"

In [17]:
text_2='''Helen is unhappy with her mother. Her mother is unhappy with Helen. They are both unhappy with each other. Helen has a boyfriend. His name is Peter. Her mother doesn't like Peter. Her mother said that Peter is rude. Why did she say that? Because Peter didn't take his hat off in the house. Helen's mother says that is rude. A man should take his hat off in the house. "Your father always took his hat off in the house," Helen's mother said. "But, Mom, times are different now," Helen said. "I promise you, Peter will take his hat off next time." Helen's mother said it was too late - rude is rude.'''

Se convierten en minúsculas todas las letras del texto a trabajar

In [18]:
text2_min = text_2.lower()

El texto se tokeniza en oraciones para poder hacer la comparación con la bolsa de palabras ya establecida

In [19]:
tk_text2 = nltk. sent_tokenize(text2_min)

Se imprimen las oraciones tokenizadas

In [20]:
tk_text2

['helen is unhappy with her mother.',
 'her mother is unhappy with helen.',
 'they are both unhappy with each other.',
 'helen has a boyfriend.',
 'his name is peter.',
 "her mother doesn't like peter.",
 'her mother said that peter is rude.',
 'why did she say that?',
 "because peter didn't take his hat off in the house.",
 "helen's mother says that is rude.",
 'a man should take his hat off in the house.',
 '"your father always took his hat off in the house," helen\'s mother said.',
 '"but, mom, times are different now," helen said.',
 '"i promise you, peter will take his hat off next time."',
 "helen's mother said it was too late - rude is rude."]

Se crea una lista con el nombre matriz.
En el ciclo for para las oraciones que se encuentran en la lista de oraciones tokenizadas, se tokenizan en palabras.
Se declara una nuvea lista, en la que las palabras en el diccionario de fecuencia, se comparan con la lista recientemente creada.
Para eso se utiliza el nombre como llave para hacer la comparación.
En caso de que se encuentre se agrega 1 a la lista, si no es un 0.
Después esa lista se agrega a la lista de matriz.

In [21]:
matriz=[]
for sen in tk_text2:
    wd_sen_tk=nltk.word_tokenize(sen)
    lista=[]
    for word in frecs.keys():
        
        if word in wd_sen_tk:
            lista.append(1)
        else:
            lista.append(0)

    matriz.append(lista)

Se imprima la matriz

In [22]:
print(matriz)

[[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0]

La matriz ya creada se utiliza numpy para transformarlo como un arreglo de numpy

In [23]:
np_matriz=np.array(matriz)

Se imprime el arreglo de numpy

In [26]:
print(np_matriz)

[[1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 1 0 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 1 1 0]
 [1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]
